
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PR_CONTINUAR = 53;
  public static final int DOSPUNTOS = 12;
  public static final int DISTINTO = 23;
  public static final int POR = 16;
  public static final int CHAR = 32;
  public static final int STR = 31;
  public static final int EQUALS = 20;
  public static final int PR_SELECT = 49;
  public static final int PR_VOID = 35;
  public static final int ENTERO = 27;
  public static final int PR_DOBLE = 41;
  public static final int LLAVIZQ = 6;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int PR_CADENA = 39;
  public static final int MAYORQUE = 19;
  public static final int IGUAL = 9;
  public static final int PR_HACER = 55;
  public static final int PR_IMPRI = 44;
  public static final int CORDER = 7;
  public static final int DIVIDIDO = 17;
  public static final int OR = 25;
  public static final int PR_PDEFECT = 51;
  public static final int PR_PARA = 48;
  public static final int PR_EJECUTAR = 45;
  public static final int PR_RETORNO = 43;
  public static final int ID = 30;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int DECIMAL = 28;
  public static final int MAYOROIGUAL = 21;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int PR_CORTAR = 52;
  public static final int PR_DGLOBALES = 37;
  public static final int PR_BIN = 42;
  public static final int MODULO = 34;
  public static final int MENOS = 15;
  public static final int PR_CASO = 50;
  public static final int PR_CHAR = 40;
  public static final int MENOROIGUAL = 22;
  public static final int MENORQUE = 18;
  public static final int POTENCIA = 33;
  public static final int LLAVDER = 5;
  public static final int PUNTO = 10;
  public static final int DOLLAR = 13;
  public static final int PR_MIENTRAS = 54;
  public static final int PTCOMA = 2;
  public static final int BOOLEANO = 29;
  public static final int PR_SINO = 47;
  public static final int PR_ENTERO = 38;
  public static final int PR_SI = 46;
  public static final int PARDER = 4;
  public static final int CORIZQ = 8;
  public static final int PR_MAIN = 36;
  public static final int MAS = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "LLAVDER",
  "LLAVIZQ",
  "CORDER",
  "CORIZQ",
  "IGUAL",
  "PUNTO",
  "COMA",
  "DOSPUNTOS",
  "DOLLAR",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "MENORQUE",
  "MAYORQUE",
  "EQUALS",
  "MAYOROIGUAL",
  "MENOROIGUAL",
  "DISTINTO",
  "AND",
  "OR",
  "NOT",
  "ENTERO",
  "DECIMAL",
  "BOOLEANO",
  "ID",
  "STR",
  "CHAR",
  "POTENCIA",
  "MODULO",
  "PR_VOID",
  "PR_MAIN",
  "PR_DGLOBALES",
  "PR_ENTERO",
  "PR_CADENA",
  "PR_CHAR",
  "PR_DOBLE",
  "PR_BIN",
  "PR_RETORNO",
  "PR_IMPRI",
  "PR_EJECUTAR",
  "PR_SI",
  "PR_SINO",
  "PR_PARA",
  "PR_SELECT",
  "PR_CASO",
  "PR_PDEFECT",
  "PR_CORTAR",
  "PR_CONTINUAR",
  "PR_MIENTRAS",
  "PR_HACER"
  };
}

